### PR TITLE
Use ISO-8859-1 encoding for i18n files

### PR DESCRIPTION
**Pull request by RandomByte**
As expected by the UI5 Tooling

### CODE REVIEW

**Comment by matz3** [comment]
Encoding conversion not required based on new concept: https://github.com/SAP/ui5-tooling/pull/168

**Comment by matz3** [comment]
@RandomByte or do we want to use normal UTF-8 then?

**Comment by RandomByte** [comment]
Well, UTF8 would be nice but bloats the ui5.yaml a bit.

I don't like the current content of the _de file (containing unicode escapes) since they are hard to read.

I think I'm in favor of using normal UTF-8, without escapes and the additional ui5.yaml configuration.

**Comment by RandomByte** [comment]
Follow up: https://github.com/SAP/openui5-sample-app/pull/54

**Pull request closed without merging**
